/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.me.paneles;

import java.sql.SQLException;
import org.me.listeners.ListenerLiberarHabitaciones;
import org.me.modelos.DataBaseHelper;

/**
 *
 * @author Adrián
 */
public class PanelLiberarHabitacion extends javax.swing.JPanel {
    
    private final String dbUser;
    private final String dbPassword;

    /**
     * Creates new form PanelLiberarHabitacion
     * @param dbUser
     * @param dbPassword
     */
    public PanelLiberarHabitacion(String dbUser, String dbPassword) {
        this.dbUser = dbUser;
        this.dbPassword = dbPassword;
        initComponents();
    }
    
    /**
     * 
     * @return un arreglo de cadenas con las habitaciones ocupadas
     */
    public String[] getHabitacionesOcupadas() {
        try {
            DataBaseHelper dbh = new DataBaseHelper(getDbUser(), getDbPassword());
            dbh.iniciarConexion();
            String[] habitaciones;
            habitaciones = dbh.getHabitacionesEnServicio();
            dbh.cerrarConexion();
            return habitaciones;
        } catch (ClassNotFoundException | SQLException ex) {
            String[] rs = new String[1];
            rs[0] = "No hay habitaciones disponibles.";
            return rs;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbHabitaciones = new javax.swing.JComboBox(getHabitacionesOcupadas());
        jbLiberar = new javax.swing.JButton();

        jbLiberar.setText("Liberar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jcbHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jbLiberar)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jbLiberar)
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbLiberar;
    private javax.swing.JComboBox jcbHabitaciones;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jcbHabitaciones
     */
    public javax.swing.JComboBox getJcbHabitaciones() {
        return jcbHabitaciones;
    }

    /**
     * @return the dbUser
     */
    public String getDbUser() {
        return dbUser;
    }

    /**
     * @return the dbPassword
     */
    public String getDbPassword() {
        return dbPassword;
    }
    
    public void addListener (ListenerLiberarHabitaciones listener) {
        jbLiberar.addActionListener(listener);
    }
    
}
