/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.me.paneles;

import com.toedter.calendar.JCalendar;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import org.me.listeners.ListenerReabastecerHabitacion;
import org.me.modelos.DataBaseHelper;
import org.me.util.Message;

/**
 *
 * @author JR
 */
public class PanelReabastecimientoHabitacion extends javax.swing.JPanel {

    private final String dbUser;
    private final String dbPassword;

    /**
     * Creates new form PanelAltaEmpleado
     *
     * @param dbUser
     * @param dbPassword
     */
    public PanelReabastecimientoHabitacion(String dbUser, String dbPassword) {
        this.dbUser = dbUser;
        this.dbPassword = dbPassword;
        initComponents();
    }

    public boolean datosValidos() {
        return camposLlenos()
                && productoEncontradoValido()
                && productoDepositadoValido();
    }
    
    private boolean productoDepositadoValido () {
        try {
            Double.parseDouble(jtfProductoDepositado.getText());
            return true;
        } catch (NumberFormatException ex) {
            Message.showErrorMessage("Error en el campo del producto depositado.");
            return false;
        }
    }
    
    public String[] getProductos() {
        try {
            DataBaseHelper dbh = new DataBaseHelper(getDbUser(), getDbPassword());
            dbh.iniciarConexion();
            String[] productos;
            productos = dbh.getProductos();
            dbh.cerrarConexion();
            return productos;
        } catch (ClassNotFoundException | SQLException ex) {
            String[] rs = new String[1];
            rs[0] = "No hay productos en el inventario.";
            return rs;
        }
    }
    
    public String[] getHabitacionesOcupadas() {
        try {
            DataBaseHelper dbh = new DataBaseHelper(dbUser, dbPassword);
            dbh.iniciarConexion();
            String[] habitaciones;
            habitaciones = dbh.getHabitacionesEnServicio();
            dbh.cerrarConexion();
            return habitaciones;
        } catch (ClassNotFoundException | SQLException ex) {
            String[] rs = new String[1];
            rs[0] = "No hay habitaciones disponibles.";
            return rs;
        }
    }
    
    private boolean productoEncontradoValido () {
        try {
            Integer.parseInt(jtfProductoEncontrado.getText());
            return true;
        } catch (NumberFormatException ex) {
            Message.showErrorMessage("Error en el campo del producto encontrado.");
            return false;
        }
    }

    private boolean camposLlenos() {
        if (!jtfProductoDepositado.getText().isEmpty()
                && !jtfProductoEncontrado.getText().isEmpty()) {
            return true;
        } else {
            Message.showErrorMessage("Faltan de llenar alguno de los campos.");
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlProductoEncontrado = new javax.swing.JLabel();
        jtfProductoEncontrado = new javax.swing.JTextField();
        jlProductoDepositado = new javax.swing.JLabel();
        jtfProductoDepositado = new javax.swing.JTextField();
        jlFecha = new javax.swing.JLabel();
        jcFechaIngreso = new com.toedter.calendar.JCalendar();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlIdProducto = new javax.swing.JLabel();
        jlHorarioDeposito = new javax.swing.JLabel();
        jsHoraD = new javax.swing.JSpinner();
        jsMinutosD = new javax.swing.JSpinner();
        jbAceptar = new javax.swing.JButton();
        jlIdHabitacion = new javax.swing.JLabel();
        jcbProducto = new javax.swing.JComboBox(getProductos());
        jcbHabitacion = new javax.swing.JComboBox(getHabitacionesOcupadas());

        jlProductoEncontrado.setText("Cantidad de producto encontrado");

        jlProductoDepositado.setText("Cantidad de producto depositado");

        jlFecha.setText("Selecciona en el calendario la fecha de deposito");

        jlIdProducto.setText("Nombre del producto");

        jlHorarioDeposito.setText("Hora de deposito");

        jsHoraD.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"}));

        jsMinutosD.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"}));

        jbAceptar.setText("Aceptar");

        jlIdHabitacion.setText("ID de la habitacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlFecha)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlHorarioDeposito)
                                        .addGap(90, 90, 90)
                                        .addComponent(jsHoraD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jsMinutosD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlProductoEncontrado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfProductoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlProductoDepositado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfProductoDepositado, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlIdProducto)
                                            .addComponent(jlIdHabitacion))
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jcbHabitacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAceptar)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlProductoEncontrado)
                    .addComponent(jtfProductoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlProductoDepositado)
                    .addComponent(jtfProductoDepositado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlHorarioDeposito)
                    .addComponent(jsHoraD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsMinutosD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlFecha)
                .addGap(18, 18, 18)
                .addComponent(jcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdProducto)
                    .addComponent(jcbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdHabitacion)
                    .addComponent(jcbHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JSeparator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JButton getJbAceptar() {
        return jbAceptar;
    }

    public void setJbAceptar(JButton jbAceptar) {
        this.jbAceptar = jbAceptar;
    }

    public JCalendar getJcFechaIngreso() {
        return jcFechaIngreso;
    }

    public void setJcFechaIngreso(JCalendar jcFechaIngreso) {
        this.jcFechaIngreso = jcFechaIngreso;
    }

    public JLabel getJlFecha() {
        return jlFecha;
    }

    public void setJlFecha(JLabel jlFecha) {
        this.jlFecha = jlFecha;
    }

    public JLabel getJlHorarioDeposito() {
        return jlHorarioDeposito;
    }

    public void setJlHorarioDeposito(JLabel jlHorarioDeposito) {
        this.jlHorarioDeposito = jlHorarioDeposito;
    }

    public JLabel getJlIdHabitacion() {
        return jlIdHabitacion;
    }

    public void setJlIdHabitacion(JLabel jlIdHabitacion) {
        this.jlIdHabitacion = jlIdHabitacion;
    }

    public JLabel getJlIdProducto() {
        return jlIdProducto;
    }

    public void setJlIdProducto(JLabel jlIdProducto) {
        this.jlIdProducto = jlIdProducto;
    }

    public JLabel getJlProductoDepositado() {
        return jlProductoDepositado;
    }

    public void setJlProductoDepositado(JLabel jlProductoDepositado) {
        this.jlProductoDepositado = jlProductoDepositado;
    }

    public JLabel getJlProductoEncontrado() {
        return jlProductoEncontrado;
    }

    public void setJlProductoEncontrado(JLabel jlProductoEncontrado) {
        this.jlProductoEncontrado = jlProductoEncontrado;
    }

    public JSpinner getJsHoraD() {
        return jsHoraD;
    }

    public void setJsHoraD(JSpinner jsHoraD) {
        this.jsHoraD = jsHoraD;
    }

    public JSpinner getJsMinutosD() {
        return jsMinutosD;
    }

    public void setJsMinutosD(JSpinner jsMinutosD) {
        this.jsMinutosD = jsMinutosD;
    }

    public JTextField getJtfProductoDepositado() {
        return jtfProductoDepositado;
    }

    public void setJtfApellidoPaterno(JTextField jtfApellidoPaterno) {
        this.jtfProductoDepositado = jtfApellidoPaterno;
    }

    public JTextField getJtfProductoEncontrado() {
        return jtfProductoEncontrado;
    }

    public void setJtfNombreEmpleado(JTextField jtfNombreEmpleado) {
        this.jtfProductoEncontrado = jtfNombreEmpleado;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbAceptar;
    private com.toedter.calendar.JCalendar jcFechaIngreso;
    private javax.swing.JComboBox jcbHabitacion;
    private javax.swing.JComboBox jcbProducto;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlHorarioDeposito;
    private javax.swing.JLabel jlIdHabitacion;
    private javax.swing.JLabel jlIdProducto;
    private javax.swing.JLabel jlProductoDepositado;
    private javax.swing.JLabel jlProductoEncontrado;
    private javax.swing.JSpinner jsHoraD;
    private javax.swing.JSpinner jsMinutosD;
    private javax.swing.JTextField jtfProductoDepositado;
    private javax.swing.JTextField jtfProductoEncontrado;
    // End of variables declaration//GEN-END:variables

    public void addListener (ListenerReabastecerHabitacion listener) {
        jbAceptar.addActionListener(listener);
    }
    
    /**
     * @return the dbUser
     */
    public String getDbUser() {
        return dbUser;
    }

    /**
     * @return the dbPassword
     */
    public String getDbPassword() {
        return dbPassword;
    }

    /**
     * @return the jcbHabitacion
     */
    public javax.swing.JComboBox getJcbHabitacion() {
        return jcbHabitacion;
    }

    /**
     * @return the jcbProducto
     */
    public javax.swing.JComboBox getJcbProducto() {
        return jcbProducto;
    }
    
}
